FROM debian:stretch
LABEL maintainer=kewbitxmr@protonmail.com

# We will need these ports to use proxies and web console
EXPOSE 4444 4447 7070 9439

# Make our image up-to-date (optional)
# Install the dependencies for i2pd
RUN apt-get update -y  && \
    apt-get upgrade -y && \
    apt-get install -y  wget                            \
                        libboost-date-time1.62.0        \
                        libboost-filesystem1.62.0       \
                        libboost-program-options1.62.0  \
                        libboost-system1.62.0           \
                        libminiupnpc10               && \   

# Fetch the latest package and install it
    cd /tmp && \
    wget https://github.com/PurpleI2P/i2pd/releases/download/2.16.0/i2pd_2.16.0-1stretch1_amd64.deb && \
    dpkg -i /tmp/i2pd_2.16.0-1stretch1_amd64.deb && \
    apt-get remove -y wget && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*  /tmp/* && \

# Make the i2pd user available
    usermod -s /bin/bash i2pd

# Copy configuration files into the container
COPY i2pd.conf /etc/i2pd/i2pd.conf
COPY subscriptions.txt /etc/i2pd/subscriptions.txt
COPY tunnels.conf /etc/i2pd/tunnels.conf

# Define the entrypoint
ENTRYPOINT exec su - i2pd -c "/usr/sbin/i2pd --conf /etc/i2pd/i2pd.conf"